=== Redis backend

The service discovery has a plug-able backend using the {@link io.vertx.servicediscovery.spi.ServiceDiscoveryBackend} SPI. This is an implementation of the SPI based
on Redis.

==== Using the Redis backend

To use the Redis backend, add the following dependency to the _dependencies_ section of your build
descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-service-discovery-backend-redis</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-service-discovery-backend-redis:${maven.version}'
----

Be aware that you can have only a single implementation of the SPI in your _classpath_. If none,
the default backend is used.

==== Configuration

The backend is based on the http://vertx.io/docs/vertx-redis-client/java[vertx-redis-client].
The configuration is the client configuration as well as `key` indicating in which _key_ on Redis
the records are stored.

Here is an example:

[source,$lang]
----
{@link examples.ServiceDiscoveryBackendRedisExamples#configuration1(io.vertx.core.Vertx)}
----

It's important to note that the backend configuration is passed in the `setBackendConfiguration` method (or
`backendConfiguration` entry if you use JSON):

[source,$lang]
----
{@link examples.ServiceDiscoveryBackendRedisExamples#configuration2(io.vertx.core.Vertx)}
----
