== Vert.x Discovery Backend - Redis

The service discovery has a plug-able backend using the `link:../../apidocs/io/vertx/servicediscovery/spi/ServiceDiscoveryBackend.html[ServiceDiscoveryBackend]` SPI.

This is an implementation of the SPI based
on Redis.

== Using the Redis backend

To use the Redis backend, add the following dependency to the _dependencies_ section of your build
descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-service-discovery-backend-redis</artifactId>
  <version>3.4.0.Beta1</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-service-discovery-backend-redis:3.4.0.Beta1'
----

Be aware that you can have only a single implementation of the SPI in your _classpath_. If none,
the default backend is used.

== Configuration

The backend is based on the http://vertx.io/docs/vertx-redis-client/java[vertx-redis-client].
The configuration is the client configuration as well as `key` indicating in which _key_ on Redis
the records are stored.

Here is an example:

[source,kotlin]
----
<<<<<<< a89e02b5fcadc28e56cf842afa8eccfb3d44b6b7
import io.vertx.kotlin.core.json.*
import io.vertx.kotlin.servicediscovery.*
import io.vertx.servicediscovery.ServiceDiscovery
import io.vertx.servicediscovery.ServiceDiscoveryOptions
=======
import io.vertx.kotlin.common.json.*
import io.vertx.servicediscovery.ServiceDiscovery
>>>>>>> Don't generate deprecated Observable methods

ServiceDiscovery.create(vertx, ServiceDiscoveryOptions(
  backendConfiguration = json {
    obj(
      "host" to "127.0.0.1",
      "key" to "records"
    )
  }))

----